# Generated by Django 2.2.7 on 2022-07-20 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('firstName', models.CharField(max_length=30, null=True)),
                ('lastName', models.CharField(blank=True, max_length=30, null=True)),
                ('jobTitle', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('school', models.CharField(blank=True, max_length=150, null=True)),
                ('fbId', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('birthday', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=300, null=True)),
                ('fbId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userimage', to='user.CustomUser')),
            ],
        ),
    ]
